# alembic/script.py.mako
"""Add outbox_tasks table

Revision ID: 218fe3c1831c
Revises: 18dec8dff674
Create Date: 2025-07-04 14:25:52.277544

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '218fe3c1831c'
down_revision = '18dec8dff674'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(), nullable=False),
    sa.Column('task_kwargs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'PUBLISHED', 'FAILED', name='outbox_task_status_enum'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_tasks_status'), 'outbox_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_outbox_tasks_task_name'), 'outbox_tasks', ['task_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbox_tasks_task_name'), table_name='outbox_tasks')
    op.drop_index(op.f('ix_outbox_tasks_status'), table_name='outbox_tasks')
    op.drop_table('outbox_tasks')
    # ### end Alembic commands ###