# alembic/script.py.mako
"""Add state tracking fields to Post model

Revision ID: f56458dbcf16
Revises: 218fe3c1831c
Create Date: 2025-07-06 10:10:41.400272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f56458dbcf16'
down_revision = '218fe3c1831c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###